import turtle

def happyface_draw(x,y,sz):
    turtle.speed(0)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.forward(80)
    turtle.right(90)
    turtle.penup()
    turtle.forward(sz)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(80)
    turtle.penup()
    turtle.goto(x,y)
    turtle.right(180)
    turtle.forward(180)
    turtle.pendown()
    for i in range(180):
        turtle.forward(1)
        turtle.right(1)
happyface_draw(0,0,120)

def sadface_draw(x,y,sz) :
    turtle.speed(0)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.forward(80)
    turtle.right(90)
    turtle.penup()
    turtle.forward(sz)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(80)
    turtle.penup()
    turtle.goto(x,y)
    turtle.right(180)
    turtle.forward(270)
    turtle.right(180)
    turtle.pendown()
    for i in range(180):
        turtle.forward(1)
        turtle.left(1)
sadface_draw(0,100,120)

def surprisedface_draw(x,y,sz):
    turtle.speed(0)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.forward(80)
    turtle.right(90)
    turtle.penup()
    turtle.forward(sz)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(80)
    turtle.penup()
    turtle.goto(x,y)
    turtle.right(180)
    turtle.forward(270)
    turtle.right(180)
    turtle.pendown()
    turtle.circle(60)

surprisedface_draw(0,400,120)


